language: php

php:
    - 5.5

env:
    - ZEROMQ_VERSION=v4.0.1 CZMQ_VERSION=2.2.0 ZYRE_VERSION=1.0.0

before_install:
    - sudo apt-get update
    - sudo apt-get remove libzmq3-dev libzmq3
    - sudo apt-get install uuid-dev
    - sudo su -c "echo '/tmp/zeromq/lib' > /etc/ld.so.conf.d/zmq-travis.conf"
    - sudo su -c "echo '/tmp/czmq/lib' >> /etc/ld.so.conf.d/zmq-travis.conf"
    - sudo su -c "echo '/tmp/zyre/lib' >> /etc/ld.so.conf.d/zmq-travis.conf"
    - export PKG_CONFIG_PATH="/tmp/zeromq/lib/pkgconfig:/tmp/czmq/lib/pkgconfig:/tmp/zyre/lib/pkgconfig"

script: travis/script.sh $ZEROMQ_VERSION $CZMQ_VERSION $ZYRE_VERSION
